
final List<Map<String, dynamic>> contacts = [
  {
    'name': 'Abdul Rehman Khan',
    'phoneNumber': '+92 312 9052024',
    'photo': 'assets/ark.jpg',
    'isFavorite': false,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'Kabeer Oad',
    'phoneNumber': '+92 301 3603209',
    'photo': 'assets/kabeer.jpg',
    'isFavorite': true,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'MeerKhan Rajput',
    'phoneNumber': '+92 309 9034713',
    'photo': 'assets/meerkhan.jpg',
    'isFavorite': true,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'Ali Mahdi',
    'phoneNumber': '+92 316 1328519',
    'photo': 'assets/ali_mahdi.jpg',
    'isFavorite': false,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'Muzamil Ansari',
    'phoneNumber': '+92 316 1328519',
    'photo': 'assets/muzamil.jpeg',
    'isFavorite': false,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'Ubaid',
    'phoneNumber': '+92 316 1328519',
    'photo': 'assets/ubaid.jpg',
    'isFavorite': false,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'Parvaiz Ali',
    'phoneNumber': '+92 316 1328519',
    'photo': 'assets/parvaiz.jpg',
    'isFavorite': false,
    'call': false,
    'time': 'Null',
  },
  {
    'name': 'Rahim',
    'phoneNumber': '+92 316 1328519',
    'photo': 'assets/rahim.jpg',
    'isFavorite': false,
    'call': false,
    'time': 'Null',
  },
];
